:Author: Hallyson Almeida
:Email: hallysonh@gmail.com
:Date: 18/09/2017
:Revision: 1.0
:License: Public Domain

= Project: Mario Genius

Memory Game with Super Mario Soundtrack

== Step 1: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 2: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 genius_game                    => project folder
  ├── genius_game.ino           => main project file
  ├── notes.h                   => music notes declaration header
  ├── genius_layout.fzz         => Flitzing schema project
  ├── genius_layout_bb.png/svg  => an image of the breadboard layout
  ├── genius_layout_schem.png   => an image of the schema layout
  ├── genius_layout_pcb.png     => an image of the pcb layout
  └── ReadMe.adoc               => this file
....

=== License
This project is released under a MIT License.

=== Contributing
To contribute to this project please contact @hallysonh <hallysonh@gmail.com>

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number  | Quantity
| A1 | Arduino        | UNO-Rev3     | 1        
| R1 | 220 Resistor   | 281-220/REEL | 4       
| B1 | Button         | 2345-asdf    | 4        
| P1 | Piezo          | PKM22EPP-40  | 1        
| L1 | Blue LED       | YSL-R542B5C  | 1        
| L2 | Red LED        | UR502DC      | 1        
| L3 | Yellow LED     | L-7113YT     | 1        
| L4 | Green LED      | G502DC       | 1        
| W1 | Wires          |              | 14        
|===
